import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "fake store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-backgroundPrimary ${inter.className} flex justify-center`}
      >
        <main className="flex min-h-screen mx-4 py-8 lg:mx-[10%] max-w-screen-xl">
          {children}
        </main>
      </body>
    </html>
  );
}
